### ISSUE TITLE
Cannot build on Visual studio and cannot access the site in the readme on the instructions

### ISSUE THREAD

**Issue by iam9394** [sevstels/Ubertooth-Win#4]
I am building on VS2019 and I am getting a lot of build errors. What are the prereqs that I need to have to build this tool on windows?

**Comment by sevstels** [comment]
Post a list of errors

**Comment by iam9394** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'=': cannot convert from 'void *' to 'extra_info::hci_conn_info_req *'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	72	
Error	C2065	'ACL_LINK': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	79	
Error	C2065	'ACL_PTYPE_MASK': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	82	
Error	C3861	'ba2str': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	92	
Error	C3861	'ba2str': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	266	
Error	C3861	'bacpy': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	78	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	78	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	81	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	92	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	95	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	172	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	177	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	302	
Error	C2275	'bdaddr': illegal use of this type as an expression	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	306	
Error	C2065	'bdaddr_t': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	193	
Error	C3861	'btohs': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	144	
Error	C3861	'bt_compidtostr': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	105	
Error	C3861	'bt_free': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	108	
Error	C3861	'bt_free': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	126	
Error	C3861	'close': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	313	
Error	C2079	'di' uses undefined struct 'extra_info::hci_dev_info'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	61	
Error	C2065	'extended': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	176	
Error	C2065	'HCIGETCONNINFO': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	80	
Error	C3861	'hci_create_connection': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	81	
Error	C3861	'hci_devid': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	226	
Error	C3861	'hci_devinfo': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	65	
Error	C3861	'hci_disconnect': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	162	
Error	C3861	'hci_inquiry': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	261	
Error	C2065	'HCI_OE_USER_ENDED_CONNECTION': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	162	
Error	C3861	'hci_open_dev': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	232	
Error	C3861	'hci_read_afh_map': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	146	
Error	C3861	'hci_read_clock_offset': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	139	
Error	C3861	'hci_read_remote_ext_features': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	115	
Error	C3861	'hci_read_remote_ext_features': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	129	
Error	C3861	'hci_read_remote_features': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	112	
Error	C3861	'hci_read_remote_name': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	95	
Error	C3861	'hci_read_remote_name': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	172	
Error	C3861	'hci_read_remote_version': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	98	
Error	C3861	'htobs': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	82	
Error	C3861	'htobs': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	90	
Error	C2065	'ii': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	183	
Error	C2065	'ii': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	259	
Error	C2065	'ii': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	261	
Error	C2065	'ii': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	266	
Error	C2065	'ii': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	267	
Error	C2065	'ii': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	270	
Error	C2065	'inquiry_info': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	183	
Error	C2065	'inquiry_info': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	259	
Error	C3861	'ioctl': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	80	
Error	C2065	'IREQ_CACHE_FLUSH': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	258	
Error	C2065	'LMP_EXT_FEAT': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	114	
Error	C2065	'LMP_EXT_FEAT': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	114	
Error	C3861	'lmp_featurestostr': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	124	
Error	C3861	'lmp_vertostr': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	99	
Error	C2065	'printable_addr': undeclared identifier	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	175	
Error	C2660	'print_name_and_class': function does not take 4 arguments	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	267	
Error	C2660	'print_name_and_class': function does not take 4 arguments	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	306	
Error	C3861	'sleep': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	87	
Error	C3861	'str2ba': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	302	
Error	C3861	'usleep': identifier not found	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	161	
Error	C2079	'version' uses undefined struct 'extra_info::hci_version'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	60	
Error	LNK1120	1 unresolved externals	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-btle\ub-btle.vcxproj	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-btle.exe	1	
Error	LNK1120	2 unresolved externals	ub-dump	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-dump.exe	1	
Error	LNK1120	2 unresolved externals	ub-afh	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-afh.exe	1	
Error	LNK1120	2 unresolved externals	ub-specan	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-specan.exe	1	
Error	LNK1120	2 unresolved externals	ub-rx	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-rx.exe	1	
Error	LNK1120	2 unresolved externals	ub-debug	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-debug.exe	1	
Error	LNK1120	2 unresolved externals	ub-dfu	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-dfu.exe	1	
Error	LNK1120	2 unresolved externals	ub-ego	C:\Users\write\Downloads\Ubertooth-Win-master\x86\Release\ub-ego.exe	1	
Error	C1083	Cannot open include file: 'bluetooth/bluetooth.h': No such file or directory	ub-follow	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-follow\src\ubertooth-follow.c	21	
Error	LNK1181	cannot open input file 'ubertooth.lib'	ub-ble-beacom	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-beacom\LINK	1	
Error	C2059	syntax error: ')'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	259	
Error	C2061	syntax error: identifier 'bdaddr_t'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	53	
Error	C2061	syntax error: identifier 'bdaddr_t'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	167	
Error	C2146	syntax error: missing ';' before identifier 'bdaddr'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	193	
Error	MSB6003	The specified task executable "CL.exe" could not be run. System.IO.IOException: The process cannot access the file 'C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-util\Win32\x86\Release\ub-util.tlog' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand)
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.DeleteEmptyFile(ITaskItem[] filesToDelete)
   at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode)
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute()	ub-util	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	636	
Error	LNK2001	unresolved external symbol _sscanf	ub-dump	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-dump\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol _sscanf	ub-afh	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-afh\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol _sscanf	ub-specan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-specan\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol _sscanf	ub-rx	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-rx\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol _sscanf	ub-debug	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-debug\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol _sscanf	ub-dfu	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-dfu\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol _sscanf	ub-ego	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-ego\libusb-1.0.lib(windows_winusb.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-dump	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-dump\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-afh	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-afh\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-btle\ub-btle.vcxproj	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-btle\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-specan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-specan\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-rx	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-rx\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-debug	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-debug\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-ego	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-ego\libusb-1.0.lib(core.obj)	1	
Error	LNK2001	unresolved external symbol ___iob_func	ub-dfu	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-dfu\libusb-1.0.lib(core.obj)	1	
Error	C2027	use of undefined type 'extra_info::hci_conn_info'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	72	
Error	C2027	use of undefined type 'extra_info::hci_conn_info_req'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	72	
Error	C2027	use of undefined type 'extra_info::hci_conn_info_req'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	78	
Error	C2027	use of undefined type 'extra_info::hci_conn_info_req'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	79	
Error	C2027	use of undefined type 'extra_info::hci_conn_info_req'	ub-scan	C:\Users\write\Downloads\Ubertooth-Win-master\ubertooth-scan\src\ubertooth-scan.c	90

**Comment by iam9394** [comment]
As for the link in the readme. I'll get this upon clicking the hyperlink
Forbidden
You don't have permission to access /index.php on this server.

**Comment by sevstels** [comment]
>> Forbidden
I left this company a long time ago and probably they do not want to support this documentation further.

>>  About application "ubertooth-scan" errors
You will not be able to build this application for windows. Because this application has not been completed. It requires a ported bluez stack. Look at the headers ... the required files are missing from the assembly. If you want, try doing it yourself.

**Comment by iam9394** [comment]
Can I use the application without ubertooth-scan if you know? Man i was hoping to use this app with ubertooth on windows :(

**Comment by sevstels** [comment]
Yes, of course. Set for this application to DO NOT BUILD. Then you can successfully build the rest of the programs that do not require a stack. The rest everything works without problems. I also recommend replacing the firmware. It fixes USB communication bugs. Don't put your hopes too much on Ubertooth project. It is rather primitive and not convenient for full-fledged work with BLE.

**Comment by iam9394** [comment]
Ah, I'm primarily working on BREDR and sometimes just need to sniff BLE packets to study. Sniffers are to expensive and Ubertooth One is quite affordable. Thanks for your info. I'll tried compiling but looks like everything is looking for bluetooth.h (i guess its blueZ header)

**Comment by sevstels** [comment]
Try TI's [sniffer on the CC2540](https://www.aliexpress.com/item/4000059514865.html). It's much cheaper than Ubertooth and TI's software is much more convenient to use.

**Comment by iam9394** [comment]
Thanks for the suggestion :D
